### PR TITLE
Support CMake-only build and submoduling.

### PR DESCRIPTION
**Pull request by pvcStillInGradSchool**
This request has already been proposed in #2 and #7.

The main reason (as I understand) to use a `Makefile` as a preprocessor is to prepend two `#define` lines to `metis.h`, which then might be installed somewhere (currently in `~/local` by default). As @karypis mentioned in #2, the attempt made by @zheng-da leaves the burden of defining these macros to the user of (the installed) METIS, since the installed `metis.h`, which is copied from the source directory, has commented out these two lines.

My attempt is based on the [`configure_file()`](https://cmake.org/cmake/help/latest/command/configure_file.html) command, which sets the values of `IDXTYPEWIDTH` and `REALTYPEWIDTH` in the _configuration_ stage. The configured `metis.h`, which contains the two `#define`s, will then be used to build the targets in this project, and will be copied to `${CMAKE_INSTALL_PREFIX}/include` in the _installation_ stage. At the point of running `make install` or `ninja install` (as mentioned by @gruenich in #7), my approach has the same effect as the current `Makefile`-driven one.

### CODE REVIEW

**Comment by pvcStillInGradSchool** [comment]
The second commit is to fix another tiny problem about CMake.

When someone build METIS as a stand-alone project, both [`${CMAKE_SOURCE_DIR}`](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html) and [`${CMAKE_CURRENT_SOURCE_DIR}`](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_SOURCE_DIR.html) point to the top directory of METIS. Everything is OK.

However, if someone use METIS as a submodule of another project, say "ABC", then [`${CMAKE_SOURCE_DIR}`](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html) will point to the top directory of ABC, which means `${CMAKE_SOURCE_DIR}/GKlib` will be `ABC/GKlib`, rather than `ABC/METIS/GKlib` or `ABC/ThirdParty/METIS/GKlib`.

This can be fixed simply by replacing `${CMAKE_SOURCE_DIR}/GKlib` with `${CMAKE_CURRENT_SOURCE_DIR}/GKlib`, since [`${CMAKE_CURRENT_SOURCE_DIR}`](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_SOURCE_DIR.html) will be the top directory of the submoduled METIS.

**Comment by gruenich** [comment]
Off-topic: Do you mind rebasing your branch and making a forced push? That would reduce this MR to three commits instead of having two merges from master sitting between your changes. Thanks!

**Comment by pvcStillInGradSchool** [comment]
> Off-topic: Do you mind rebasing your branch and making a forced push? That would reduce this MR to three commits instead of having two merges from master sitting between your changes. Thanks!

Thanks for your advice. The commit history has been cleaned up.

**Comment by pvcStillInGradSchool** [comment]
The maintainer has [made GKlib an external dependency](https://github.com/KarypisLab/METIS/commit/96ae6e7f44cf849b89794dc2f48757acf4859353). So this PR cannot been rebased on the targeting branch now.

**Pull request closed without merging**
