### PR TITLE
expose libmetis API/install libmetis/GKlib headers

### LINKED ISSUE #8: [Feature Request] Expose libmetis API
First off, I just want to say this piece of software has been very very useful to the numerical math community and I would like to extend my appreciation for creating and maintaining METIS.

I was hoping that if there is any interest in exposing the libmetis/ header functionality. Right now when I install METIS based on the instructions `metis.h` is installed, but it does not expose the libmetis.so API. In order for me to use the code in `libmetis.so` I end up keeping a copy of METIS in my project folder and just manually linking from there. Would it be possible to install the other header files (like `metislib.h`, `struct.h`, etc. in `libmetis/` to the install include folder along with `metis.h`?

Or maybe I am not properly understanding how to call `libmetis.so` functionality in C++ based on the current installation instructions.

### PR DESCRIPTION
**Pull request by acxz**
Resolves #8

### CODE REVIEW

**Comment by acxz** [comment]
@karypis do you mind taking a look at this?

**Comment by acxz** [comment]
@karypis friendly ping

**Comment by acxz** [comment]
@karypis can you provide closure to this PR?

**Comment by acxz** [comment]
@karypis it would be much appreciated if you could take a look at this PR. Thank you.

**Comment by karypis** [comment]
I do not understand why you want to have GKlib's header files installed? They are not required for using Metis' library. Metis' metis.h is already installed per include/CMakeLists.txt

**Comment by acxz** [comment]
While GKlib's header files are not needed for `metis.h`, they are needed for `metislib.h`.

**Comment by karypis** [comment]
Exposing internal routines to external programs can lead to issues down the road, as internal routines can change.

**Comment by acxz** [comment]
I see, thank you for taking the time to discuss this.

**Comment by varunagrawal** [comment]
@karypis what would you recommend as the way to go if one is trying to create a custom Separator function.
For example, METIS has the `METIS_ComputeVertexSeparator` function, but for research purposes, I may want to tweak the function and add some different capability, naming the function as `METIS_ComputeVertexSeparator2`. This would require me to include `metislib.h` in my project.

Is there an alternative to this?

**Comment by varunagrawal** [comment]
@karypis gentle reminder.

**Pull request closed without merging**
