### PR TITLE
Fix various source comment and doc typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L ifset,ned,nd,`

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: metis typos seen in downstream [ElmerCSC](https://github.com/ElmerCSC/elmerfem/pulls?q=is%3Apr+author%3Aluzpaz+sort%3Aupdated-desc) repo.

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
bump

**Comment by karypis** [comment]
Thanks!

**Pull request merged**
